-- Communal Services DB — Sample Queries

-- 1. Clients with privileges
-- Selects clients who have privileges, including their name, email, privilege type, and privilege percentage.
SELECT c.FullName AS ClientName, c.Email, p.PrivilegeType, p.Percentage
FROM Client c
LEFT JOIN Privilege p ON c.PrivilegeID = p.PrivilegeID
WHERE c.PrivilegeID IS NOT NULL;


-- 2. Active discounts on services
-- Displays services that currently have active discounts, along with the discount name and percentage.
SELECT s.ServiceName, s.Tariff, s.Unit, d.DiscountName, d.Percentage AS DiscountPercentage
FROM Service s
LEFT JOIN Discount d ON s.ServiceID = d.ServiceID
WHERE CURDATE() BETWEEN d.StartDate AND d.EndDate;


-- 3. Unresolved complaints with client names
-- Shows all unresolved client complaints, including the complaint date, description, and the client's name.
SELECT comp.ComplaintID, comp.ComplaintDate, comp.Description, c.FullName AS ClientName
FROM Complaint comp
JOIN Client c ON comp.ClientID = c.ClientID
WHERE comp.Status != 'Solved';


-- 4. Notifications sent by administrators to clients
-- Shows all notifications sent by administrators to clients, with date, message text, and the names of the admin and client.
SELECT n.NotificationID, n.NotificationDate, n.Message, a.FullName AS AdminName, c.FullName AS ClientName
FROM Notification n
LEFT JOIN Administrator a ON n.AdminID = a.AdminID
JOIN Client c ON n.ClientID = c.ClientID;


-- 5. Complaint count per client
-- Counts the number of complaints filed by each client and displays the client's name, email, and complaint count.
SELECT c.FullName AS ClientName, c.Email, COUNT(comp.ComplaintID) AS ComplaintCount
FROM Client c
LEFT JOIN Complaint comp ON c.ClientID = comp.ClientID
GROUP BY c.ClientID, c.FullName, c.Email;


-- 6. Clients and their current debt
-- Shows a list of clients along with their current outstanding debt.
SELECT c.ClientID, c.FullName, c.Email, GetClientDebt(c.ClientID) AS CurrentDebt
FROM Client c;


-- 7. Total payments per client
-- Displays all clients together with the total amount of their payments.
SELECT c.ClientID, c.FullName, GetTotalPaymentsForClient(c.ClientID) AS TotalPayments
FROM Client c;


-- 8. Apartments with total invoice payment amounts
-- Displays all apartments together with the total amount of payments made on invoices associated with each apartment.
SELECT a.ApartmentID, a.Address,
    (SELECT SUM(p.Amount)
     FROM Payment p
     JOIN Invoice i ON p.InvoiceID = i.InvoiceID
     JOIN Meter m ON i.MeterID = m.MeterID
     WHERE m.ApartmentID = a.ApartmentID) AS TotalPayments
FROM Apartment a;


-- 9. Services with total revenue
-- Shows all services together with the total revenue generated by each one.
SELECT s.ServiceID, s.ServiceName,
    (SELECT SUM(p.Amount)
     FROM Payment p
     JOIN Invoice i ON p.InvoiceID = i.InvoiceID
     WHERE i.ServiceID = s.ServiceID) AS TotalRevenue
FROM Service s;


-- 10. Clients with apartment counts
-- Displays a list of clients with the number of apartments they own, ordered by apartment count in descending order.
SELECT c.ClientID, c.FullName, COUNT(a.ApartmentID) AS ApartmentCount
FROM Client c
LEFT JOIN Apartment a ON c.ClientID = a.ClientID
GROUP BY c.ClientID, c.FullName
ORDER BY ApartmentCount DESC;


-- 11. Calculating the amount due for "Sewage Disposal" based on water supply usage
-- Calculates the amount due for the "Sewage Disposal" service based on each client's water supply usage.
SELECT c.ClientID, c.FullName,
    SUM(m.CurrentReading) AS TotalWaterUsage,
    (SUM(m.CurrentReading) * ws.Tariff) AS WasteServiceAmount
FROM Client c
JOIN Apartment a ON c.ClientID = a.ClientID
JOIN Meter m ON a.ApartmentID = m.ApartmentID
JOIN Service s ON s.ServiceName = 'Water supply'
JOIN Service ws ON ws.ServiceName = 'Sewage Disposal'
WHERE m.MeterType = 'Water'
GROUP BY c.ClientID, c.FullName, ws.Tariff;


-- 12. Clients and their total electricity payments
-- Displays clients together with the total amount of their electricity payments.
SELECT c.ClientID, c.FullName,
    (SELECT SUM(p.Amount)
     FROM Payment p
     JOIN Invoice i ON p.InvoiceID = i.InvoiceID
     JOIN Service s ON i.ServiceID = s.ServiceID
     WHERE s.ServiceName = 'Electricity' AND i.MeterID IN
         (SELECT m.MeterID
          FROM Meter m
          JOIN Apartment a ON m.ApartmentID = a.ApartmentID
          WHERE a.ClientID = c.ClientID)) AS TotalElectricityPayment
FROM Client c;


-- 13. Services with average invoice amount
-- Lists services along with the average invoice amount for each one.
SELECT s.ServiceID, s.ServiceName, AVG(i.TotalAmount) AS AvgInvoiceAmount
FROM Service s
JOIN Invoice i ON s.ServiceID = i.ServiceID
GROUP BY s.ServiceID, s.ServiceName
ORDER BY AvgInvoiceAmount DESC;


-- 14. Clients who have never filed a complaint
SELECT c.ClientID, c.FullName, c.Email
FROM Client c
LEFT JOIN Complaint comp ON c.ClientID = comp.ClientID
WHERE comp.ComplaintID IS NULL;


-- 15. Number of apartments by type
SELECT ApartmentType, COUNT(ApartmentID) AS ApartmentCount
FROM Apartment
GROUP BY ApartmentType
ORDER BY ApartmentCount DESC;


-- 16. Streets with the highest total overdue debt
-- Groups overdue invoices by street, showing the number of distinct debtors, the total debt, and the average debt per resident.
SELECT
    SUBSTRING_INDEX(a.Address, ',', 1) AS Street,
    COUNT(DISTINCT c.ClientID) AS DebtorCount,
    SUM(i.TotalAmount) AS TotalDebt,
    AVG(i.TotalAmount) AS AvgDebtPerResident
FROM
    Apartment a
JOIN
    Client c ON a.ClientID = c.ClientID
JOIN
    Meter m ON a.ApartmentID = m.ApartmentID
JOIN
    Invoice i ON m.MeterID = i.MeterID
WHERE
    i.Status = 'Overdue'
GROUP BY
    Street
ORDER BY
    TotalDebt DESC;


-- 17. Active privileges with the total number of clients using them
SELECT p.PrivilegeType, p.Percentage, COUNT(c.ClientID) AS ClientCount
FROM Privilege p
LEFT JOIN Client c ON p.PrivilegeID = c.PrivilegeID
GROUP BY p.PrivilegeType, p.Percentage
ORDER BY ClientCount DESC;


-- 18. Clients who own more than one apartment
SELECT c.ClientID, c.FullName, COUNT(a.ApartmentID) AS ApartmentCount
FROM Client c
JOIN Apartment a ON c.ClientID = a.ClientID
GROUP BY c.ClientID, c.FullName
HAVING ApartmentCount > 1
ORDER BY ApartmentCount DESC;


-- 19. Services with the maximum tariff
SELECT ServiceID, ServiceName, Tariff
FROM Service
WHERE Tariff = (SELECT MAX(Tariff) FROM Service);


-- 20. Clients who received a notification in the current month
SELECT DISTINCT c.ClientID, c.FullName
FROM Client c
JOIN Notification n ON c.ClientID = n.ClientID
WHERE MONTH(n.NotificationDate) = MONTH(CURDATE())
  AND YEAR(n.NotificationDate) = YEAR(CURDATE());


-- 21. Clients with the highest total payments across all services
SELECT c.ClientID, c.FullName, SUM(p.Amount) AS TotalPayments
FROM Client c
JOIN Apartment a ON c.ClientID = a.ClientID
JOIN Meter m ON a.ApartmentID = m.ApartmentID
JOIN Invoice i ON m.MeterID = i.MeterID
JOIN Payment p ON i.InvoiceID = p.InvoiceID
GROUP BY c.ClientID, c.FullName
ORDER BY TotalPayments DESC;
