-- Index on Service.ServiceName, created for showing query optimizations(example query below).
-- Primary key and foreign key indexes were auto-generated by DataGrip on table creation.
CREATE INDEX idx_service_name ON Service(ServiceName);

-- Example query.
EXPLAIN SELECT c.ClientID, c.FullName,
(SELECT SUM(p.Amount)
 FROM Payment p
 JOIN Invoice i ON p.InvoiceID = i.InvoiceID
 JOIN Service s ON i.ServiceID = s.ServiceID
 WHERE s.ServiceName = 'Electricity' AND i.MeterID IN
       (SELECT m.MeterID
        FROM Meter m
        JOIN Apartment a ON m.ApartmentID = a.ApartmentID
        WHERE a.ClientID = c.ClientID)) AS TotalElectricityPayment
FROM Client c;
